{% set name = "medchem" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/medchem-{{ version }}.tar.gz
  sha256: d90383fc9cff0d42c373fa3e4bfe018fad91d1e48d305d990abc73a293471423

build:
  entry_points:
    - medchem = medchem.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - typer
    - loguru
    - tqdm
    - numpy
    - lark
    - pandas
    - networkx
    - datamol >=0.10

test:
  imports:
    - medchem
  commands:
    # - pip check  # NOTE(hadim): fails cuz of datamol...
    - medchem --help
  requires:
    - pip

about:
  home: https://github.com/datamol-io/medchem
  summary: 'Medchem: Molecular filtering for drug discovery.'
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - hadim
