context:
  name: medchem
  version: "2.1.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/medchem-${{ version }}.tar.gz
  sha256: 6634e144e2a7f7baed34ac268bda06184e069b35ce8a5af8ce17ecdfa4a50bab

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77
    - setuptools-scm >=8
    - pip
  run:
    - python >=${{ python_min }}
    - datamol >=0.12.5
    - fsspec >=2023.9.2
    - lark >=1.2
    - loguru >=0.7
    - networkx >=3.2
    - numpy >=1.26
    - pandas >=2.2
    - rdkit >=2024.9.1
    - typer >=0.16

tests:
  - python:
      imports:
        - medchem
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - python ${{ python_min }}.*
        - datamol 0.12.5
    script:
      - medchem --help
      - python -c "from medchem.utils.graph import score_symmetry; assert score_symmetry('CC(C)(C)') == 1"

about:
  summary: 'Medchem: Molecular filtering for drug discovery.'
  license: Apache-2.0
  license_file: LICENSE.md
  homepage: https://github.com/datamol-io/medchem

extra:
  recipe-maintainers:
    - maclandrol
    - hadim
